// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mycompany/customerservice/service/v1/customer_service.proto
// Protobuf Java Version: 4.32.1

package com.mycompany.customerservice.service.v1;

@com.google.protobuf.Generated
public final class CustomerServiceOuterClass extends com.google.protobuf.GeneratedFile {
  private CustomerServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      CustomerServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetCustomerRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mycompany.customerservice.service.v1.GetCustomerRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 customer_id = 1 [json_name = "customerId"];</code>
     * @return The customerId.
     */
    int getCustomerId();
  }
  /**
   * Protobuf type {@code mycompany.customerservice.service.v1.GetCustomerRequest}
   */
  public static final class GetCustomerRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:mycompany.customerservice.service.v1.GetCustomerRequest)
      GetCustomerRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        GetCustomerRequest.class.getName());
    }
    // Use GetCustomerRequest.newBuilder() to construct.
    private GetCustomerRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetCustomerRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest.class, com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest.Builder.class);
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 1;
    private int customerId_ = 0;
    /**
     * <code>int32 customer_id = 1 [json_name = "customerId"];</code>
     * @return The customerId.
     */
    @java.lang.Override
    public int getCustomerId() {
      return customerId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (customerId_ != 0) {
        output.writeInt32(1, customerId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (customerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, customerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest)) {
        return super.equals(obj);
      }
      com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest other = (com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest) obj;

      if (getCustomerId()
          != other.getCustomerId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mycompany.customerservice.service.v1.GetCustomerRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mycompany.customerservice.service.v1.GetCustomerRequest)
        com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest.class, com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest.Builder.class);
      }

      // Construct using com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        customerId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_descriptor;
      }

      @java.lang.Override
      public com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest getDefaultInstanceForType() {
        return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest build() {
        com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest buildPartial() {
        com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest result = new com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.customerId_ = customerId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest) {
          return mergeFrom((com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest other) {
        if (other == com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest.getDefaultInstance()) return this;
        if (other.getCustomerId() != 0) {
          setCustomerId(other.getCustomerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                customerId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int customerId_ ;
      /**
       * <code>int32 customer_id = 1 [json_name = "customerId"];</code>
       * @return The customerId.
       */
      @java.lang.Override
      public int getCustomerId() {
        return customerId_;
      }
      /**
       * <code>int32 customer_id = 1 [json_name = "customerId"];</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(int value) {

        customerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 customer_id = 1 [json_name = "customerId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        customerId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mycompany.customerservice.service.v1.GetCustomerRequest)
    }

    // @@protoc_insertion_point(class_scope:mycompany.customerservice.service.v1.GetCustomerRequest)
    private static final com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest();
    }

    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCustomerRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetCustomerRequest>() {
      @java.lang.Override
      public GetCustomerRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetCustomerRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCustomerRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetCustomerReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mycompany.customerservice.service.v1.GetCustomerReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    java.util.List<com.mycompany.customerservice.model.v1.CustomerModel.Customer> 
        getCustomersList();
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    com.mycompany.customerservice.model.v1.CustomerModel.Customer getCustomers(int index);
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    int getCustomersCount();
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    java.util.List<? extends com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder> 
        getCustomersOrBuilderList();
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder getCustomersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mycompany.customerservice.service.v1.GetCustomerReply}
   */
  public static final class GetCustomerReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:mycompany.customerservice.service.v1.GetCustomerReply)
      GetCustomerReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        GetCustomerReply.class.getName());
    }
    // Use GetCustomerReply.newBuilder() to construct.
    private GetCustomerReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetCustomerReply() {
      customers_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply.class, com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply.Builder.class);
    }

    public static final int CUSTOMERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.mycompany.customerservice.model.v1.CustomerModel.Customer> customers_;
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    @java.lang.Override
    public java.util.List<com.mycompany.customerservice.model.v1.CustomerModel.Customer> getCustomersList() {
      return customers_;
    }
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder> 
        getCustomersOrBuilderList() {
      return customers_;
    }
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    @java.lang.Override
    public int getCustomersCount() {
      return customers_.size();
    }
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    @java.lang.Override
    public com.mycompany.customerservice.model.v1.CustomerModel.Customer getCustomers(int index) {
      return customers_.get(index);
    }
    /**
     * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    @java.lang.Override
    public com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder getCustomersOrBuilder(
        int index) {
      return customers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < customers_.size(); i++) {
        output.writeMessage(1, customers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < customers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, customers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply)) {
        return super.equals(obj);
      }
      com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply other = (com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply) obj;

      if (!getCustomersList()
          .equals(other.getCustomersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCustomersCount() > 0) {
        hash = (37 * hash) + CUSTOMERS_FIELD_NUMBER;
        hash = (53 * hash) + getCustomersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mycompany.customerservice.service.v1.GetCustomerReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mycompany.customerservice.service.v1.GetCustomerReply)
        com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply.class, com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply.Builder.class);
      }

      // Construct using com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (customersBuilder_ == null) {
          customers_ = java.util.Collections.emptyList();
        } else {
          customers_ = null;
          customersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.internal_static_mycompany_customerservice_service_v1_GetCustomerReply_descriptor;
      }

      @java.lang.Override
      public com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply getDefaultInstanceForType() {
        return com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply build() {
        com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply buildPartial() {
        com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply result = new com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply result) {
        if (customersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            customers_ = java.util.Collections.unmodifiableList(customers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.customers_ = customers_;
        } else {
          result.customers_ = customersBuilder_.build();
        }
      }

      private void buildPartial0(com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply) {
          return mergeFrom((com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply other) {
        if (other == com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply.getDefaultInstance()) return this;
        if (customersBuilder_ == null) {
          if (!other.customers_.isEmpty()) {
            if (customers_.isEmpty()) {
              customers_ = other.customers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCustomersIsMutable();
              customers_.addAll(other.customers_);
            }
            onChanged();
          }
        } else {
          if (!other.customers_.isEmpty()) {
            if (customersBuilder_.isEmpty()) {
              customersBuilder_.dispose();
              customersBuilder_ = null;
              customers_ = other.customers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              customersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetCustomersFieldBuilder() : null;
            } else {
              customersBuilder_.addAllMessages(other.customers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.mycompany.customerservice.model.v1.CustomerModel.Customer m =
                    input.readMessage(
                        com.mycompany.customerservice.model.v1.CustomerModel.Customer.parser(),
                        extensionRegistry);
                if (customersBuilder_ == null) {
                  ensureCustomersIsMutable();
                  customers_.add(m);
                } else {
                  customersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mycompany.customerservice.model.v1.CustomerModel.Customer> customers_ =
        java.util.Collections.emptyList();
      private void ensureCustomersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          customers_ = new java.util.ArrayList<com.mycompany.customerservice.model.v1.CustomerModel.Customer>(customers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.mycompany.customerservice.model.v1.CustomerModel.Customer, com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder, com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder> customersBuilder_;

      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public java.util.List<com.mycompany.customerservice.model.v1.CustomerModel.Customer> getCustomersList() {
        if (customersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customers_);
        } else {
          return customersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public int getCustomersCount() {
        if (customersBuilder_ == null) {
          return customers_.size();
        } else {
          return customersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public com.mycompany.customerservice.model.v1.CustomerModel.Customer getCustomers(int index) {
        if (customersBuilder_ == null) {
          return customers_.get(index);
        } else {
          return customersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder setCustomers(
          int index, com.mycompany.customerservice.model.v1.CustomerModel.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.set(index, value);
          onChanged();
        } else {
          customersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder setCustomers(
          int index, com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.set(index, builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder addCustomers(com.mycompany.customerservice.model.v1.CustomerModel.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.add(value);
          onChanged();
        } else {
          customersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder addCustomers(
          int index, com.mycompany.customerservice.model.v1.CustomerModel.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.add(index, value);
          onChanged();
        } else {
          customersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder addCustomers(
          com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.add(builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder addCustomers(
          int index, com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.add(index, builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder addAllCustomers(
          java.lang.Iterable<? extends com.mycompany.customerservice.model.v1.CustomerModel.Customer> values) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customers_);
          onChanged();
        } else {
          customersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder clearCustomers() {
        if (customersBuilder_ == null) {
          customers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          customersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public Builder removeCustomers(int index) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.remove(index);
          onChanged();
        } else {
          customersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder getCustomersBuilder(
          int index) {
        return internalGetCustomersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder getCustomersOrBuilder(
          int index) {
        if (customersBuilder_ == null) {
          return customers_.get(index);  } else {
          return customersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public java.util.List<? extends com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder> 
           getCustomersOrBuilderList() {
        if (customersBuilder_ != null) {
          return customersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customers_);
        }
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder addCustomersBuilder() {
        return internalGetCustomersFieldBuilder().addBuilder(
            com.mycompany.customerservice.model.v1.CustomerModel.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder addCustomersBuilder(
          int index) {
        return internalGetCustomersFieldBuilder().addBuilder(
            index, com.mycompany.customerservice.model.v1.CustomerModel.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .mycompany.customerservice.model.v1.Customer customers = 1 [json_name = "customers"];</code>
       */
      public java.util.List<com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder> 
           getCustomersBuilderList() {
        return internalGetCustomersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mycompany.customerservice.model.v1.CustomerModel.Customer, com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder, com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder> 
          internalGetCustomersFieldBuilder() {
        if (customersBuilder_ == null) {
          customersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mycompany.customerservice.model.v1.CustomerModel.Customer, com.mycompany.customerservice.model.v1.CustomerModel.Customer.Builder, com.mycompany.customerservice.model.v1.CustomerModel.CustomerOrBuilder>(
                  customers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          customers_ = null;
        }
        return customersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mycompany.customerservice.service.v1.GetCustomerReply)
    }

    // @@protoc_insertion_point(class_scope:mycompany.customerservice.service.v1.GetCustomerReply)
    private static final com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply();
    }

    public static com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCustomerReply>
        PARSER = new com.google.protobuf.AbstractParser<GetCustomerReply>() {
      @java.lang.Override
      public GetCustomerReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetCustomerReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCustomerReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mycompany.customerservice.service.v1.CustomerServiceOuterClass.GetCustomerReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mycompany_customerservice_service_v1_GetCustomerReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mycompany_customerservice_service_v1_GetCustomerReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;mycompany/customerservice/service/v1/c" +
      "ustomer_service.proto\022$mycompany.custome" +
      "rservice.service.v1\0327mycompany/customers" +
      "ervice/model/v1/customer_model.proto\"5\n\022" +
      "GetCustomerRequest\022\037\n\013customer_id\030\001 \001(\005R" +
      "\ncustomerId\"^\n\020GetCustomerReply\022J\n\tcusto" +
      "mers\030\001 \003(\0132,.mycompany.customerservice.m" +
      "odel.v1.CustomerR\tcustomers2\222\001\n\017Customer" +
      "Service\022\177\n\013GetCustomer\0228.mycompany.custo" +
      "merservice.service.v1.GetCustomerRequest" +
      "\0326.mycompany.customerservice.service.v1." +
      "GetCustomerReplyBQ\n(com.mycompany.custom" +
      "erservice.service.v1\252\002$MyCompany.Custome" +
      "rService.Service.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mycompany.customerservice.model.v1.CustomerModel.getDescriptor(),
        });
    internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mycompany_customerservice_service_v1_GetCustomerRequest_descriptor,
        new java.lang.String[] { "CustomerId", });
    internal_static_mycompany_customerservice_service_v1_GetCustomerReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mycompany_customerservice_service_v1_GetCustomerReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mycompany_customerservice_service_v1_GetCustomerReply_descriptor,
        new java.lang.String[] { "Customers", });
    descriptor.resolveAllFeaturesImmutable();
    com.mycompany.customerservice.model.v1.CustomerModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
