# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mycompany.customerservice.service.v1 import customer_service_pb2 as mycompany_dot_customerservice_dot_service_dot_v1_dot_customer__service__pb2


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCustomer = channel.unary_unary(
                '/mycompany.customerservice.service.v1.CustomerService/GetCustomer',
                request_serializer=mycompany_dot_customerservice_dot_service_dot_v1_dot_customer__service__pb2.GetCustomerRequest.SerializeToString,
                response_deserializer=mycompany_dot_customerservice_dot_service_dot_v1_dot_customer__service__pb2.GetCustomerReply.FromString,
                _registered_method=True)


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomer,
                    request_deserializer=mycompany_dot_customerservice_dot_service_dot_v1_dot_customer__service__pb2.GetCustomerRequest.FromString,
                    response_serializer=mycompany_dot_customerservice_dot_service_dot_v1_dot_customer__service__pb2.GetCustomerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mycompany.customerservice.service.v1.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mycompany.customerservice.service.v1.CustomerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mycompany.customerservice.service.v1.CustomerService/GetCustomer',
            mycompany_dot_customerservice_dot_service_dot_v1_dot_customer__service__pb2.GetCustomerRequest.SerializeToString,
            mycompany_dot_customerservice_dot_service_dot_v1_dot_customer__service__pb2.GetCustomerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
