# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mycompany/customerservice/service/v1/customer_service.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'mycompany/customerservice/service/v1/customer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mycompany.customerservice.model.v1 import customer_model_pb2 as mycompany_dot_customerservice_dot_model_dot_v1_dot_customer__model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;mycompany/customerservice/service/v1/customer_service.proto\x12$mycompany.customerservice.service.v1\x1a\x37mycompany/customerservice/model/v1/customer_model.proto\"5\n\x12GetCustomerRequest\x12\x1f\n\x0b\x63ustomer_id\x18\x01 \x01(\x05R\ncustomerId\"^\n\x10GetCustomerReply\x12J\n\tcustomers\x18\x01 \x03(\x0b\x32,.mycompany.customerservice.model.v1.CustomerR\tcustomers2\x92\x01\n\x0f\x43ustomerService\x12\x7f\n\x0bGetCustomer\x12\x38.mycompany.customerservice.service.v1.GetCustomerRequest\x1a\x36.mycompany.customerservice.service.v1.GetCustomerReplyBQ\n(com.mycompany.customerservice.service.v1\xaa\x02$MyCompany.CustomerService.Service.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mycompany.customerservice.service.v1.customer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.mycompany.customerservice.service.v1\252\002$MyCompany.CustomerService.Service.V1'
  _globals['_GETCUSTOMERREQUEST']._serialized_start=158
  _globals['_GETCUSTOMERREQUEST']._serialized_end=211
  _globals['_GETCUSTOMERREPLY']._serialized_start=213
  _globals['_GETCUSTOMERREPLY']._serialized_end=307
  _globals['_CUSTOMERSERVICE']._serialized_start=310
  _globals['_CUSTOMERSERVICE']._serialized_end=456
# @@protoc_insertion_point(module_scope)
